###
POST https://greeting-api-g0mh.onrender.com/api/greet
content-type: application/json

{
	"language" : "xhosa",
	"greeting" : "Molo"
}

###
POST https://greeting-api-g0mh.onrender.com/api/greet
content-type: application/json

{
	"language" : "Zulu",
	"greeting" : "Sawubona"
}
